---
kind: pipeline
type: docker
name: Build FluentD Image

concurrency:
  limit: 1

clone:
  depth: 1

steps:

  - name: docker build (${DRONE_BRANCH}-latest)
    image: plugins/docker
    settings:
      mirror: dockerhub.nexus.diesel.net
      registry: docker.nexus.diesel.net
      username: 
        from_secret: nexus_user
      password:
        from_secret: nexus_pass
      repo: docker.nexus.diesel.net/fluentd
      tags:
        - ${DRONE_BRANCH}-latest
    when:
      event:
        - push



  - name: docker build (${DRONE_TAG})
    image: plugins/docker
    settings:
      mirror: dockerhub.nexus.diesel.net
      registry: docker.nexus.diesel.net
      username: 
        from_secret: nexus_user
      password:
        from_secret: nexus_pass
      repo: docker.nexus.diesel.net/fluentd
      tags:
        - latest
        - ${DRONE_TAG}
    when:
      event:
        - tag

trigger:
  branch:
    - development
    - stable
  event:
    - push
    - tag
...
