version: '3.8'
services: 

  daemon:
    image: {{ docker_registry }}/fluentd:latest
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
      - /etc/localtime:/etc/localtime
      - {{ data_dir }}/:/fluentd/log/
      - {{ config_dir }}/:/fluentd/etc/
      - /var/lib/docker/containers/:/var/lib/docker/containers/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      #https://github.com/fluent/fluentd-kubernetes-daemonset#run-as-root
      - FLUENT_UID=0
    deploy:
      mode: global
      restart_policy:
        condition: any
      resources:
          limits:
            cpus: '2.0'
          reservations:
            # https://docs.fluentd.org/deployment/performance-tuning-single-process#multi-workers
            cpus: '1.0'
